server:
  addr: ":33306" # The port on which the proxy listens, mysql-server, supports direct connection of mysql-client

debug:  # Control to enable debug mode
  enable: true
  port: 17878

# mysql
mysql:
  addr: "192.168.2.80:3306"
  user: "root"
  password: "123456"
  dbname: "zta"
  minAlive: 1 # Specifies the minimum number of open connections the pool will attempt to maintain
  maxAlive: 64 # Specifies the maximum number of open connections the pool will attempt to maintain
  maxIdle: 4 # Maximum number of idle connections

# Tenant list
userlist:
  - user: host1
    password: host1

# p2p config
p2p:
  enable: false
  service_discovery_id: "p2p_sqlproxy_service_test"
  service_command_topic: "p2p_sqlproxy_service_topic_test"
  service_discover_mode: "advertise" # advertise or announce
  node_host_ip: "127.0.0.1" #local ipv4 ip
  node_host_port: 0 # any port 
