server:
  addr: ":33306" # The port on which the proxy listens, mysql-server, supports direct connection of mysql-client

debug:  # Control to enable debug mode
  enable: true
  port: 17878

# mysql configurations for different access levels
mysql:
  admin:
    addr: "192.168.2.80:3306"
    user: "admin_user"
    password: "admin_pass"
    dbname: "exampledb"
    minAlive: 1
    maxAlive: 64
    maxIdle: 4
  readonly:
    addr: "192.168.2.80:3306"
    user: "readonly_user"
    password: "readonly_pass"
    dbname: "exampledb"
    minAlive: 1
    maxAlive: 64
    maxIdle: 4

# Tenant list
userlist:
  - user: root
    password: 123456

# p2p config for different access levels
p2p:
  admin:
    enable: false
    service_discovery_id: "p2p_sqlproxy_admin_service"
    service_command_topic: "p2p_sqlproxy_admin_topic"
    service_discover_mode: "advertise"
    node_host_ip: "127.0.0.1"
    node_host_port: 0
  readonly:
    enable: false
    service_discovery_id: "p2p_sqlproxy_readonly_service"
    service_command_topic: "p2p_sqlproxy_readonly_topic"
    service_discover_mode: "advertise"
    node_host_ip: "127.0.0.1"
    node_host_port: 0
